# Generated by Django 3.2 on 2023-05-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_question', models.IntegerField(unique=True, verbose_name='ID вопроса')),
                ('question', models.TextField(verbose_name='Текст вопроса')),
                ('answer', models.TextField(verbose_name='Текст ответа')),
                ('created_at', models.TextField(verbose_name='Дата создания вопроса')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
